name:          कोड गाइड @mdo द्वारा
description:   Standards for developing flexible, durable, and sustainable HTML and CSS.
url:           http://codeguide.co

markdown:      rdiscount
permalink:     pretty
pygments:      true
