name:          Code Guide by @mdo
description:   लचीला, टिकाऊ, और टिकाऊ HTML और CSS के विकास के लिए मानक
url:           http://codeguide.co

markdown:      rdiscount
permalink:     pretty
pygments:      true
