name:          @mdo द्वारा संहिता गाइड
description:   लचीला, टिकाऊ, और टिकाऊ एचटीएमएल और सीएसएस के विकास के लिए मानक।
url:           http://codeguide.co

markdown:      rdiscount
permalink:     pretty
pygments:      true
future:        true
